import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "tertiary-fixed-dim": "#cfc4c6",
        "on-tertiary-fixed": "#201a1c",
        "on-error-container": "#93000a",
        "surface-container-highest": "#ece0e2",
        "secondary-container": "#dd2f33",
        "surface-container": "#f7ebed",
        "surface-bright": "#fff8f8",
        "secondary": "#b90d1d",
        "inverse-surface": "#352f31",
        "on-secondary-fixed-variant": "#930012",
        "inverse-primary": "#c0c1ff",
        "surface": "#fff8f8",
        "surface-container-high": "#f1e5e8",
        "on-background": "#201a1c",
        "on-tertiary-container": "#faedf0",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#464554",
        "tertiary-container": "#746b6d",
        "inverse-on-surface": "#faeef0",
        "surface-tint": "#484dd1",
        "on-primary-container": "#f1efff",
        "outline": "#767686",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary": "#5b5355",
        "error": "#ba1a1a",
        "on-surface": "#201a1c",
        "tertiary-fixed": "#ece0e2",
        "on-secondary-fixed": "#410004",
        "surface-variant": "#ece0e2",
        "on-primary-fixed": "#04006d",
        "on-tertiary-fixed-variant": "#4c4547",
        "outline-variant": "#c6c5d6",
        "on-primary-fixed-variant": "#2e31b9",
        "secondary-fixed-dim": "#ffb3ad",
        "surface-container-lowest": "#ffffff",
        "background": "#fff8f8",
        "primary": "#3e42c7",
        "secondary-fixed": "#ffdad7",
        "on-tertiary": "#ffffff",
        "primary-container": "#585de1",
        "surface-container-low": "#fdf1f3",
        "primary-fixed-dim": "#c0c1ff",
        "primary-fixed": "#e1e0ff",
        "surface-dim": "#e3d7da"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
      screens: {
        'tablet': '768px',
        'desktop': '1024px',
      },
    },
  },
  plugins: [],
};
export default config;